"""Add demographic fields to Paciente model

Revision ID: 2e3faf89adec
Revises: ba12d4d3f00f
Create Date: 2025-07-05 00:52:18.741479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3faf89adec'
down_revision = 'ba12d4d3f00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
    op.add_column('paciente', sa.Column('edad', sa.Integer(), nullable=True))
    op.add_column('paciente', sa.Column('peso', sa.Float(), nullable=True))
    op.add_column('paciente', sa.Column('altura', sa.Integer(), nullable=True))
    op.add_column('paciente', sa.Column('sexo', sa.String(length=20), nullable=True))
    op.add_column('paciente', sa.Column('actividad_fisica', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paciente', 'actividad_fisica')
    op.drop_column('paciente', 'sexo')
    op.drop_column('paciente', 'altura')
    op.drop_column('paciente', 'peso')
    op.drop_column('paciente', 'edad')
    op.drop_column('paciente', 'fecha_nacimiento')
    # ### end Alembic commands ###
