"""Add show_clinic_logo_pdf to User model

Revision ID: 33a4fb67214e
Revises: 388b60732bed
Create Date: 2025-07-19 04:13:34.196651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a4fb67214e'
down_revision = '388b60732bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Paso 1: Añadir la columna 'show_clinic_logo_pdf' como anulable (nullable=True)
    # Esto permite que las filas existentes no fallen inmediatamente al no tener un valor.
    op.execute('ALTER TABLE "user" ADD COLUMN IF NOT EXISTS show_clinic_logo_pdf BOOLEAN')

    # Paso 2: Actualizar todas las filas existentes en la tabla 'user'
    # para establecer 'show_clinic_logo_pdf' a TRUE donde sea NULL.
    # Esto asegura que todas las filas tengan un valor antes de hacer la columna NOT NULL.
    op.execute('UPDATE "user" SET show_clinic_logo_pdf = TRUE WHERE show_clinic_logo_pdf IS NULL')

    # Paso 3: Alterar la columna 'show_clinic_logo_pdf' para que no sea anulable (nullable=False)
    # Esto solo se hace después de que todas las filas existentes han sido pobladas con un valor.
    op.alter_column('user', 'show_clinic_logo_pdf',
               existing_type=sa.Boolean(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Para revertir, simplemente eliminamos la columna.
    op.drop_column('user', 'show_clinic_logo_pdf')
    # ### end Alembic commands ###
