"""Agrega campo ruta_notas_ai_pdf a Visita

Revision ID: 388b60732bed
Revises: b6121e948f68
Create Date: 2025-07-11 07:30:25.632562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388b60732bed'
down_revision = 'b6121e948f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visita', sa.Column('ruta_notas_ai_pdf', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visita', 'ruta_notas_ai_pdf')
    # ### end Alembic commands ###
