"""Add document config preferences to User model

Revision ID: 753ef1033a9c
Revises: 33a4fb67214e
Create Date: 2025-07-20 04:56:48.038435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753ef1033a9c'
down_revision = '000000000001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Añade todas las nuevas columnas booleanas.
    # Usamos server_default=sa.true() para poblar las filas existentes con 'true'.
    # Esto es crucial porque nullable=False causaría un error en tablas con datos.
    op.add_column('user', sa.Column('show_clinic_name_pdf', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('user', sa.Column('show_clinic_logo_pdf', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('user', sa.Column('show_clinic_address_pdf', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('user', sa.Column('show_clinic_phone_pdf', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('user', sa.Column('show_clinic_website_pdf', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('user', sa.Column('show_doctor_license_pdf', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('user', sa.Column('show_doctor_phone_pdf', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('user', sa.Column('show_doctor_bio_pdf', sa.Boolean(), nullable=False, server_default=sa.true()))

    # Después de añadir las columnas y poblarlas, podemos eliminar el valor por defecto del lado del servidor.
    # Esto permite que el 'default=True' en el modelo de SQLAlchemy maneje los valores por defecto para nuevas inserciones
    # sin una restricción permanente a nivel de base de datos.
    op.alter_column('user', 'show_clinic_name_pdf', existing_type=sa.Boolean(), server_default=None)
    op.alter_column('user', 'show_clinic_logo_pdf', existing_type=sa.Boolean(), server_default=None)
    op.alter_column('user', 'show_clinic_address_pdf', existing_type=sa.Boolean(), server_default=None)
    op.alter_column('user', 'show_clinic_phone_pdf', existing_type=sa.Boolean(), server_default=None)
    op.alter_column('user', 'show_clinic_website_pdf', existing_type=sa.Boolean(), server_default=None)
    op.alter_column('user', 'show_doctor_license_pdf', existing_type=sa.Boolean(), server_default=None)
    op.alter_column('user', 'show_doctor_phone_pdf', existing_type=sa.Boolean(), server_default=None)
    op.alter_column('user', 'show_doctor_bio_pdf', existing_type=sa.Boolean(), server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Elimina las columnas en el orden inverso a su creación.
    op.drop_column('user', 'show_doctor_bio_pdf')
    op.drop_column('user', 'show_doctor_phone_pdf')
    op.drop_column('user', 'show_doctor_license_pdf')
    op.drop_column('user', 'show_clinic_website_pdf')
    op.drop_column('user', 'show_clinic_phone_pdf')
    op.drop_column('user', 'show_clinic_address_pdf')
    op.drop_column('user', 'show_clinic_logo_pdf')
    op.drop_column('user', 'show_clinic_name_pdf')
    # ### end Alembic commands ###