"""Agregar campo porciones a PlanNutricional

Revision ID: 756fa755fbe1
Revises: 73ff12c18b56
Create Date: 2025-07-05 00:37:23.290857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756fa755fbe1'
down_revision = '73ff12c18b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE paciente DROP COLUMN IF EXISTS sexo')
    op.execute('ALTER TABLE paciente DROP COLUMN IF EXISTS peso')
    op.execute('ALTER TABLE paciente DROP COLUMN IF EXISTS altura')
    op.execute('ALTER TABLE paciente DROP COLUMN IF EXISTS peso')
    op.execute('ALTER TABLE paciente DROP COLUMN IF EXISTS fecha_nacimiento')
    op.execute('ALTER TABLE paciente DROP COLUMN IF EXISTS edad')
    op.execute('ALTER TABLE paciente DROP COLUMN IF EXISTS actividad_fisica')
    op.add_column('plan_nutricional', sa.Column('porciones', sa.Text(), nullable=True))
    op.drop_column('plan_nutricional', 'estado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_nutricional', sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('plan_nutricional', 'porciones')
    op.add_column('paciente', sa.Column('actividad_fisica', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('altura', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('sexo', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
