"""Add estado column to plan_nutricional

Revision ID: 91a84e39437e
Revises: 2e3faf89adec
Create Date: 2025-07-06 01:14:20.017784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a84e39437e'
down_revision = '2e3faf89adec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paciente', 'peso')
    op.drop_column('paciente', 'fecha_nacimiento')
    op.drop_column('paciente', 'edad')
    op.drop_column('paciente', 'actividad_fisica')
    op.drop_column('paciente', 'sexo')
    op.drop_column('paciente', 'altura')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_nutricional', 'estado')
    op.add_column('paciente', sa.Column('altura', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('sexo', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('actividad_fisica', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
