"""Initial migration

Revision ID: 92cb0b0b9197
Revises: 99fa1ac5ec9d
Create Date: 2025-08-05 18:59:05.865964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cb0b0b9197'
down_revision = '99fa1ac5ec9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
