"""Initial migration

Revision ID: 99fa1ac5ec9d
Revises: 
Create Date: 2025-08-05 18:58:17.087462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fa1ac5ec9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estadisticas_demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minutos_grabados', sa.Integer(), nullable=True),
    sa.Column('visitas_generadas', sa.Integer(), nullable=True),
    sa.Column('pacientes_creados', sa.Integer(), nullable=True),
    sa.Column('documentos_creados', sa.Integer(), nullable=True),
    sa.Column('documentos_resumidos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospectos_interes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('especialidad', sa.String(length=150), nullable=True),
    sa.Column('carne_medico', sa.String(length=100), nullable=True),
    sa.Column('identificacion', sa.String(length=50), nullable=True),
    sa.Column('lugar_trabajo', sa.String(length=255), nullable=True),
    sa.Column('consentimiento', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('especialidad', sa.String(length=150), nullable=True),
    sa.Column('licencia_profesional', sa.String(length=100), nullable=True),
    sa.Column('identificacion', sa.String(length=50), nullable=True),
    sa.Column('telefono_profesional', sa.String(length=50), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('url_foto_perfil', sa.String(length=512), nullable=True),
    sa.Column('clinica_nombre', sa.String(length=200), nullable=True),
    sa.Column('clinica_direccion', sa.Text(), nullable=True),
    sa.Column('clinica_telefono', sa.String(length=50), nullable=True),
    sa.Column('clinica_website', sa.String(length=200), nullable=True),
    sa.Column('lugar_trabajo', sa.String(length=255), nullable=True),
    sa.Column('url_logo_clinica', sa.String(length=512), nullable=True),
    sa.Column('show_clinic_name_pdf', sa.Boolean(), nullable=False),
    sa.Column('show_clinic_logo_pdf', sa.Boolean(), nullable=False),
    sa.Column('show_clinic_address_pdf', sa.Boolean(), nullable=False),
    sa.Column('show_clinic_phone_pdf', sa.Boolean(), nullable=False),
    sa.Column('show_clinic_website_pdf', sa.Boolean(), nullable=False),
    sa.Column('show_doctor_license_pdf', sa.Boolean(), nullable=False),
    sa.Column('show_doctor_phone_pdf', sa.Boolean(), nullable=False),
    sa.Column('show_doctor_bio_pdf', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identificacion'),
    sa.UniqueConstraint('licencia_profesional')
    )
    op.create_table('message_programado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('identificacion_documento', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('estado_tratamiento', sa.String(length=100), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paciente_email'), 'paciente', ['email'], unique=False)
    op.create_index(op.f('ix_paciente_identificacion_documento'), 'paciente', ['identificacion_documento'], unique=False)
    op.create_index(op.f('ix_paciente_nombre'), 'paciente', ['nombre'], unique=False)
    op.create_table('respuesta_rapida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dateTime', sa.String(length=50), nullable=False),
    sa.Column('assignedTo', sa.String(length=100), nullable=False),
    sa.Column('guests', sa.Text(), nullable=True),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nota_fecha'), 'nota', ['fecha'], unique=False)
    op.create_table('visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('plantilla', sa.String(length=100), nullable=True),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('resumen_ai', sa.Text(), nullable=True),
    sa.Column('notas_ai', sa.Text(), nullable=True),
    sa.Column('ruta_notas_ai_pdf', sa.String(length=512), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('idioma_detectado', sa.String(length=20), nullable=True),
    sa.Column('tipo_visita', sa.String(length=50), nullable=False),
    sa.Column('duracion_grabacion_segundos', sa.Integer(), nullable=True),
    sa.Column('archivos_adjuntos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visita_fecha'), 'visita', ['fecha'], unique=False)
    op.create_index(op.f('ix_visita_paciente_id'), 'visita', ['paciente_id'], unique=False)
    op.create_table('plan_nutricional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('contenido_json', sa.Text(), nullable=False),
    sa.Column('notas_adicionales', sa.Text(), nullable=True),
    sa.Column('ruta_pdf_almacenada', sa.String(length=512), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visita_id'], ['visita.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_nutricional_fecha_emision'), 'plan_nutricional', ['fecha_emision'], unique=False)
    op.create_index(op.f('ix_plan_nutricional_medico_id'), 'plan_nutricional', ['medico_id'], unique=False)
    op.create_index(op.f('ix_plan_nutricional_paciente_id'), 'plan_nutricional', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_plan_nutricional_visita_id'), 'plan_nutricional', ['visita_id'], unique=False)
    op.create_table('receta_medica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('medicamentos_json', sa.Text(), nullable=False),
    sa.Column('diagnostico_relacionado', sa.Text(), nullable=True),
    sa.Column('validez_dias', sa.Integer(), nullable=True),
    sa.Column('notas_adicionales_receta', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visita_id'], ['visita.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receta_medica_fecha_emision'), 'receta_medica', ['fecha_emision'], unique=False)
    op.create_index(op.f('ix_receta_medica_medico_id'), 'receta_medica', ['medico_id'], unique=False)
    op.create_index(op.f('ix_receta_medica_paciente_id'), 'receta_medica', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_receta_medica_visita_id'), 'receta_medica', ['visita_id'], unique=False)
    op.create_table('referencia_medica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_referente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('especialidad_referida', sa.String(length=150), nullable=False),
    sa.Column('medico_referido_nombre', sa.String(length=150), nullable=True),
    sa.Column('institucion_referida', sa.String(length=200), nullable=True),
    sa.Column('motivo_referencia', sa.Text(), nullable=True),
    sa.Column('resumen_clinico_relevante', sa.Text(), nullable=True),
    sa.Column('estudios_adjuntos_info', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['medico_referente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visita_id'], ['visita.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referencia_medica_fecha_emision'), 'referencia_medica', ['fecha_emision'], unique=False)
    op.create_index(op.f('ix_referencia_medica_medico_referente_id'), 'referencia_medica', ['medico_referente_id'], unique=False)
    op.create_index(op.f('ix_referencia_medica_paciente_id'), 'referencia_medica', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_referencia_medica_visita_id'), 'referencia_medica', ['visita_id'], unique=False)
    op.create_table('registro_actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre_display', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visita.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_actividad_fecha'), 'registro_actividad', ['fecha'], unique=False)
    op.create_index(op.f('ix_registro_actividad_visita_id'), 'registro_actividad', ['visita_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_actividad_visita_id'), table_name='registro_actividad')
    op.drop_index(op.f('ix_registro_actividad_fecha'), table_name='registro_actividad')
    op.drop_table('registro_actividad')
    op.drop_index(op.f('ix_referencia_medica_visita_id'), table_name='referencia_medica')
    op.drop_index(op.f('ix_referencia_medica_paciente_id'), table_name='referencia_medica')
    op.drop_index(op.f('ix_referencia_medica_medico_referente_id'), table_name='referencia_medica')
    op.drop_index(op.f('ix_referencia_medica_fecha_emision'), table_name='referencia_medica')
    op.drop_table('referencia_medica')
    op.drop_index(op.f('ix_receta_medica_visita_id'), table_name='receta_medica')
    op.drop_index(op.f('ix_receta_medica_paciente_id'), table_name='receta_medica')
    op.drop_index(op.f('ix_receta_medica_medico_id'), table_name='receta_medica')
    op.drop_index(op.f('ix_receta_medica_fecha_emision'), table_name='receta_medica')
    op.drop_table('receta_medica')
    op.drop_index(op.f('ix_plan_nutricional_visita_id'), table_name='plan_nutricional')
    op.drop_index(op.f('ix_plan_nutricional_paciente_id'), table_name='plan_nutricional')
    op.drop_index(op.f('ix_plan_nutricional_medico_id'), table_name='plan_nutricional')
    op.drop_index(op.f('ix_plan_nutricional_fecha_emision'), table_name='plan_nutricional')
    op.drop_table('plan_nutricional')
    op.drop_index(op.f('ix_visita_paciente_id'), table_name='visita')
    op.drop_index(op.f('ix_visita_fecha'), table_name='visita')
    op.drop_table('visita')
    op.drop_index(op.f('ix_nota_fecha'), table_name='nota')
    op.drop_table('nota')
    op.drop_table('tarea')
    op.drop_table('respuesta_rapida')
    op.drop_index(op.f('ix_paciente_nombre'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_identificacion_documento'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_email'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_table('message_programado')
    op.drop_table('user')
    op.drop_table('prospectos_interes')
    op.drop_table('estadisticas_demo')
    # ### end Alembic commands ###
