"""Add demographic fields to Paciente model

Revision ID: 9ef861a381f2
Revises: 91a84e39437e
Create Date: 2025-07-06 13:39:32.855881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef861a381f2'
down_revision = '91a84e39437e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
    op.add_column('paciente', sa.Column('edad', sa.Integer(), nullable=True))
    op.add_column('paciente', sa.Column('peso', sa.Float(), nullable=True))
    op.add_column('paciente', sa.Column('altura', sa.Integer(), nullable=True))
    op.add_column('paciente', sa.Column('sexo', sa.String(length=20), nullable=True))
    op.add_column('paciente', sa.Column('actividad_fisica', sa.String(length=50), nullable=True))
    op.execute('ALTER TABLE plan_nutricional DROP COLUMN IF EXISTS estado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_nutricional', sa.Column('estado', sa.VARCHAR(length=50), server_default=sa.text("'activo'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('paciente', 'actividad_fisica')
    op.drop_column('paciente', 'sexo')
    op.drop_column('paciente', 'altura')
    op.drop_column('paciente', 'peso')
    op.drop_column('paciente', 'edad')
    op.drop_column('paciente', 'fecha_nacimiento')
    # ### end Alembic commands ###
