"""Add estado column to PlanNutricional table

Revision ID: b6121e948f68
Revises: 9ef861a381f2
Create Date: 2025-07-07 12:01:01.645928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6121e948f68'
down_revision = '9ef861a381f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paciente', 'altura')
    op.drop_column('paciente', 'fecha_nacimiento')
    op.drop_column('paciente', 'actividad_fisica')
    op.drop_column('paciente', 'sexo')
    op.drop_column('paciente', 'edad')
    op.drop_column('paciente', 'peso')
    op.add_column('plan_nutricional', sa.Column('estado', sa.String(length=50), nullable=False, server_default='activo'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_nutricional', 'estado')
    op.add_column('paciente', sa.Column('peso', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('sexo', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('actividad_fisica', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('paciente', sa.Column('altura', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
