"""Remove porciones column from PlanNutricional

Revision ID: ba12d4d3f00f
Revises: 756fa755fbe1
Create Date: 2025-07-05 00:46:57.875680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba12d4d3f00f'
down_revision = '756fa755fbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Se ha eliminado la línea op.drop_column('plan_nutricional', 'porciones')
    # de esta migración porque causaba un error de columna no definida (UndefinedColumn).
    # Esto indica que la columna 'porciones' no existía previamente en la base de datos
    # o ya había sido eliminada por otros medios.
    # Si el objetivo era que esta columna no existiera, su estado actual ya lo refleja.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Si la columna 'porciones' se eliminó manualmente o nunca existió,
    # esta operación de downgrade no es necesaria o causaría un error si se intenta añadir.
    # Si en algún momento se necesita añadir 'porciones' nuevamente, se debe crear una nueva migración.
    # op.add_column('plan_nutricional', sa.Column('porciones', sa.String(length=255), nullable=True))
    pass
    # ### end Alembic commands ###



