"""Un mensaje que describa tu cambio

Revision ID: d41fc78f3e1a
Revises: 693cc7b750d3
Create Date: 2025-07-31 23:01:26.289593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41fc78f3e1a'
down_revision = '693cc7b750d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estadisticas_demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minutos_grabados', sa.Integer(), nullable=True),
    sa.Column('visitas_generadas', sa.Integer(), nullable=True),
    sa.Column('pacientes_creados', sa.Integer(), nullable=True),
    sa.Column('documentos_creados', sa.Integer(), nullable=True),
    sa.Column('documentos_resumidos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadisticas_demo')
    # ### end Alembic commands ###
